# The Infrastructure as Code Action also supports integrating with GitHub Code Scanning and can show issues in the
# GitHub Security tab. When run, a snyk.sarif file will be generated which can be uploaded to GitHub Code Scanning.
permissions:
  actions: read
  contents: read
  security-events: write

name: Snyk Infrastructure as Code
on: push
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Snyk to check configuration files for security issues
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: .
          args: --scan=resource-changes --severity-threshold=low
          #sarif: true
      #- name: Remove the sarif file
      #  run: rm snyk.sarif
      - name: Display all files in the root
        run: ls -al
      #- name: Display Sarif File
       # run: cat snyk.sarif